# Based on https://github.com/derekvincent/awesome-list-template/blob/main/.github/workflows/setup-awesome-list.yml
name: setup-awesome-list

on:
  workflow_dispatch:

env:
  DEFAULT_BRANCH: "main"
  SETUP_BRANCH: "setup"
  PLACEHOLDER_REPO: "derekvincent/awesome-list-template"

jobs:
  setup-awesome-list:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
      pull-requests: write

    steps:
      - name: create-update-branch
        uses: peterjgrainger/action-create-branch@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ env.SETUP_BRANCH }}
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ env.SETUP_BRANCH }}
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: setup-template
        shell: bash
        run: |
          echo $GITHUB_REPOSITORY
          rm -rf history config latest-changes.md README.md awesome-list.yaml ./.github/workflows/setup-best-of-list.yml CONTRIBUTING.md create-awesome-list.md
          mkdir -p ./config
          cp ./template/footer.md ./config/footer.md
          cp ./template/header.md ./config/header.md
          cp ./template/awesome-list.yaml ./awesome-list.yaml
          cp ./template/CONTRIBUTING.md ./CONTRIBUTING.md
          rm -rf ./template/
          sed -i 's:${{ env.PLACEHOLDER_REPO }}:'$GITHUB_REPOSITORY':g' ./awesome-list.yaml
          sed -i 's:${{ env.PLACEHOLDER_REPO }}:'$GITHUB_REPOSITORY':g' ./config/footer.md
          sed -i 's:${{ env.PLACEHOLDER_REPO }}:'$GITHUB_REPOSITORY':g' ./config/header.md
          sed -i 's:${{ env.PLACEHOLDER_REPO }}:'$GITHUB_REPOSITORY':g' ./CONTRIBUTING.md
          sed -i 's:'$(echo "${{ env.PLACEHOLDER_REPO }}" | sed "s:.*/::")':'$(echo "$GITHUB_REPOSITORY" | sed "s:.*/::")':g' ./config/header.md

      - name: create-pull-request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: ${{ env.SETUP_BRANCH }}
          base: ${{ env.DEFAULT_BRANCH }}
          title: "Initial setup for awesome lists"
          body: |
            To finish this setup: Select **Merge pull request** below and **Confirm merge**.
            This will create the initial structure for your awesome list.
          commit-message: Initial setup for awesome lists
          labels: setup
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: sync-labels
        uses: EndBug/label-sync@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-file: ".github/labels.yml"
